// js/tools-data.js - AI工具数据库
const TOOLS_DATA = [
    {
        id: "chatgpt",
        name: "ChatGPT",
        icon: "💬",
        tag: "AI对话",
        category: "chat",
        description: "OpenAI开发的知名AI对话助手，支持文字、图片、语音多模态交互，可用于写作、编程、翻译、分析等各类任务。",
        price: "免费 + Plus $20/月",
        rating: 4.8,
        url: "https://chat.openai.com",
        featured: true,
        pros: ["强大的逻辑推理能力", "支持插件扩展", "多模态输入支持", "活跃的开发者社区"],
        cons: ["免费版有使用限制", "偶尔服务器繁忙", "数据隐私存在争议"],
        bestFor: ["内容创作", "编程辅助", "学习研究", "日常问答"],
        alternatives: ["claude", "gemini", "perplexity"]
    },
    {
        id: "claude",
        name: "Claude",
        icon: "🤖",
        tag: "AI对话",
        category: "chat",
        description: "Anthropic公司开发的AI助手，以安全性、可控性和长上下文窗口著称，擅长长文档分析和精确写作。",
        price: "免费 + Pro $20/月",
        rating: 4.7,
        url: "https://claude.ai",
        featured: true,
        pros: ["200K超长上下文", "更安全的输出", "擅长分析和写作", "引用来源可追溯"],
        cons: ["创意写作不如GPT-4", "部分地区访问受限"],
        bestFor: ["长文档分析", "学术研究", "内容审核", "代码审查"],
        alternatives: ["chatgpt", "gemini"]
    },
    {
        id: "midjourney",
        name: "Midjourney",
        icon: "🎨",
        tag: "AI绘画",
        category: "image",
        description: "知名的AI图像生成工具，以高质量、艺术感强的输出著称，广泛应用于创意设计、概念艺术和营销素材制作。",
        price: "$10/月起",
        rating: 4.6,
        url: "https://midjourney.com",
        featured: true,
        pros: ["画质业界顶尖", "艺术风格丰富", "社区活跃", "版本迭代快"],
        cons: ["需要Discord使用", "无免费试用", "付费才能商用"],
        bestFor: ["概念设计", "艺术创作", "广告素材", "游戏美术"],
        alternatives: ["dalle", "stable-diffusion", "leonardo"]
    },
    {
        id: "github-copilot",
        name: "GitHub Copilot",
        icon: "💻",
        tag: "AI编程",
        category: "code",
        description: "GitHub推出的AI编程助手，深度集成VS Code等主流 IDE，提供智能代码补全、生成和重构建议。",
        price: "$10/月（学生免费）",
        rating: 4.5,
        url: "https://github.com/features/copilot",
        featured: true,
        pros: ["IDE深度集成", "支持多种编程语言", "学生免费", "GitHub生态联动"],
        cons: ["需要订阅付费", "偶尔生成有bug的代码", "依赖网络连接"],
        bestFor: ["软件开发", "代码学习", "快速原型", "重构优化"],
        alternatives: ["cursor", "codeium", "tabnine"]
    },
    {
        id: "cursor",
        name: "Cursor",
        icon: "⚡",
        tag: "AI编程",
        category: "code",
        description: "基于VS Code的AI增强代码编辑器，集成了强大的AI对话、代码生成和智能重构功能，被誉为"最懂程序员的AI工具"。",
        price: "免费 + Pro $20/月",
        rating: 4.7,
        url: "https://cursor.sh",
        featured: true,
        pros: ["基于VS Code，易上手", "AI对话式编程", "代码库级上下文理解", "免费版够用"],
        cons: ["需要联网使用AI功能", "部分高级功能需付费"],
        bestFor: ["全栈开发", "代码重构", "学习新技术", "快速迭代"],
        alternatives: ["github-copilot", "codeium"]
    },
    {
        id: "runway-gen3",
        name: "Runway Gen-3",
        icon: "🎬",
        tag: "AI视频",
        category: "video",
        description: "Runway推出的新一代AI视频生成模型，支持文本生成视频、图片转视频、视频风格迁移等功能，画质和连贯性大幅提升。",
        price: "$35/月起",
        rating: 4.4,
        url: "https://runwayml.com",
        featured: true,
        pros: ["画质业界领先", "多种视频AI功能", "风格控制精细", "API可集成"],
        cons: ["价格较高", "生成速度中等", "免费额度有限"],
        bestFor: ["短视频创作", "广告制作", "概念视频", "视觉效果"],
        alternatives: ["pika", "gen-2", "sora"]
    },
    {
        id: "notion-ai",
        name: "Notion AI",
        icon: "📝",
        tag: "效率工具",
        category: "productivity",
        description: "Notion集成的AI助手，可在笔记、文档、知识库中直接调用AI进行写作、总结、翻译和问答，无缝融入工作流。",
        price: "$10/月（加Notion订阅）",
        rating: 4.3,
        url: "https://notion.s.com",
        featured: false,
        pros: ["与Notion深度集成", "支持多种AI任务", "上下文理解强", "团队协作友好"],
        cons: ["需要Notion付费版", "AI功能需额外付费", "大文档处理慢"],
        bestFor: ["知识管理", "团队协作文档", "会议纪要", "内容规划"],
        alternatives: ["mem", "reflect", "logseq"]
    },
    {
        id: "elevenlabs",
        name: "ElevenLabs",
        icon: "🎵",
        tag: "AI音频",
        category: "audio",
        description: "知名的AI语音合成平台，提供高度自然的多语言TTS（文本转语音）和语音克隆功能，广泛应用于有声书、视频配音和虚拟助手。",
        price: "免费 + $11/月起",
        rating: 4.5,
        url: "https://elevenlabs.io",
        featured: false,
        pros: ["语音自然度极高", "支持29+语言", "语音克隆功能强大", "API接入方便"],
        cons: ["付费版才支持商用", "克隆语音需谨慎使用", "免费版额度有限"],
        bestFor: ["视频配音", "有声书制作", "虚拟主播", "客服语音"],
        alternatives: ["azure-tts", "google-tts", "amazon-polly"]
    },
    {
        id: "jasper",
        name: "Jasper AI",
        icon: "✍️",
        tag: "AI写作",
        category: "writing",
        description: "面向企业和营销团队的AI写作工具，擅长生成广告文案、博客文章、社交媒体内容和邮件营销文案，支持Brand Voice定制。",
        price: "$49/月起",
        rating: 4.2,
        url: "https://jasper.ai",
        featured: false,
        pros: ["营销模板丰富", "支持Brand Voice", "多语言输出", "团队协作功能"],
        cons: ["价格较高", "创意写作不如GPT-4", "学习曲线存在"],
        bestFor: ["营销文案", "企业博客", "社交媒体", "邮件营销"],
        alternatives: ["copyai", "writesonic", "chatgpt"]
    },
    {
        id: "semrush-ai",
        name: "Semrush AI Writing Assistant",
        icon: "📈",
        tag: "营销工具",
        category: "marketing",
        description: "Semrush推出的AI写作助手，集成SEO优化建议，帮助创作符合搜索引擎排名要求的高质量内容，适合内容营销和SEO团队。",
        price: "包含在Semrush订阅中（$129.95/月）",
        rating: 4.1,
        url: "https://semrush.com",
        featured: false,
        pros: ["深度SEO集成", "实时优化建议", "关键词研究联动", "内容评分系统"],
        cons: ["Semrush订阅价格高", "适合SEO专业人士", "学习成本较高"],
        bestFor: ["SEO内容创作", "博客优化", "竞品分析", "关键词策略"],
        alternatives: ["surfer-seo", "clearscope", "fasewriter"]
    },
    {
        id: "leonardo",
        name: "Leonardo.Ai",
        icon: "🖼️",
        tag: "AI绘画",
        category: "image",
        description: "新兴的AI图像生成平台，提供丰富的模型选择、精细的编辑工具和友好的免费额度，适合个人创作者和小型团队。",
        price: "免费 + $10/月起",
        rating: 4.3,
        url: "https://leonardo.ai",
        featured: false,
        pros: ["免费额度 generous", "模型选择丰富", "编辑工具强大", "社区画廊可参考"],
        cons: ["画质略逊于Midjourney", "界面相对复杂", "高级功能需付费"],
        bestFor: ["概念设计", "游戏美术", "社交媒体配图", "个人创作"],
        alternatives: ["midjourney", "stable-diffusion", "dalle"]
    },
    {
        id: "perplexity",
        name: "Perplexity AI",
        icon: "🔍",
        tag: "AI搜索",
        category: "chat",
        description: "AI驱动的搜索引擎，结合大模型对话能力和实时网络搜索，提供带引用的准确答案，是传统搜索引擎的AI升级版。",
        price: "免费 + Pro $20/月",
        rating: 4.4,
        url: "https://perplexity.ai",
        featured: false,
        pros: ["答案带引用来源", "实时网络信息", "界面简洁易用", "支持追问式搜索"],
        cons: ["深度研究能力有限", "部分高级功能需付费", "中文内容覆盖较少"],
        bestFor: ["快速调研", "事实核查", "学习新领域", "替代搜索引擎"],
        alternatives: ["chatgpt", "gemini", "you-com"]
    },
    // ========== 新增工具 2026-05-20 ==========
    {
        id: "gemini",
        name: "Google Gemini",
        icon: "💎",
        tag: "AI对话",
        category: "chat",
        description: "谷歌推出的多模态AI助手，深度集成Google搜索和Google Workspace，支持文本、图片、音频、视频多模态输入，Gemini 2.0 Flash响应速度极快。",
        price: "免费 + Advanced $19.99/月",
        rating: 4.6,
        url: "https://gemini.google.com",
        featured: true,
        pros: ["与Google生态深度集成", "响应速度极快", "支持超长上下文", "多模态能力强"],
        cons: ["对话深度不如Claude", "中文理解略逊", "Advanced版价格较高"],
        bestFor: ["Google生态用户", "快速问答", "多模态分析", "学生学习"],
        alternatives: ["chatgpt", "claude", "perplexity"]
    },
    {
        id: "copilot-microsoft",
        name: "Microsoft Copilot",
        icon: "🪟",
        tag: "AI对话",
        category: "chat",
        description: "微软基于OpenAI模型打造的AI助手，深度集成Windows、Office、Edge浏览器，支持联网搜索和图片生成（DALL-E 3），个人和企业用户均可使用。",
        price: "免费 + Pro $20/月",
        rating: 4.4,
        url: "https://copilot.microsoft.com",
        featured: false,
        pros: ["深度集成Windows/Office", "支持DALL-E 3图片生成", "联网搜索能力强", "企业版安全可靠"],
        cons: ["对话质量略逊于ChatGPT", "需要微软账号", "Pro版性价比一般"],
        bestFor: ["Windows用户", "Office办公", "企业应用", "日常辅助"],
        alternatives: ["chatgpt", "gemini", "claude"]
    },
    {
        id: "ideogram-v2",
        name: "Ideogram v2",
        icon: "🖼️",
        tag: "AI绘画",
        category: "image",
        description: "专注于文字渲染的AI图像生成工具，v2版本在画质和文字准确性上大幅提升，是唯一能稳定生成准确文字的AI绘画工具，适合海报、Logo设计场景。",
        price: "免费 + $20/月",
        rating: 4.5,
        url: "https://ideogram.ai",
        featured: true,
        pros: ["文字渲染业界最强", "画质提升明显", "操作简单", "免费额度充足"],
        cons: ["艺术风格略逊Midjourney", "高级功能需付费", "社区功能较少"],
        bestFor: ["海报设计", "Logo概念", "带文字的图片", "社交媒体图"],
        alternatives: ["midjourney", "dalle", "leonardo"]
    },
    {
        id: "adobe-firefly",
        name: "Adobe Firefly",
        icon: "🔥",
        tag: "AI绘画",
        category: "image",
        description: "Adobe推出的商用安全AI图像处理套件，深度集成Photoshop、Illustrator等Creative Cloud软件，所有生成内容可商用，无版权风险。",
        price: "免费 + $4.99/月起",
        rating: 4.3,
        url: "https://www.adobe.com/products/firefly.html",
        featured: false,
        pros: ["100%商用安全", "深度集成Adobe生态", "与工作流无缝衔接", "版权清晰"],
        cons: ["需Adobe账号", "独立版功能有限", "画质略逊独立AI工具"],
        bestFor: ["商业设计", "Adobe用户", "需要商用的场景", "专业修图"],
        alternatives: ["midjourney", "ideogram-v2", "leonardo"]
    },
    {
        id: "stable-diffusion-xl",
        name: "Stable Diffusion XL",
        icon: "🎨",
        tag: "AI绘画",
        category: "image",
        description: "Stability AI推出的开源AI绘画模型，SDXL在画质和提示词理解上大幅提升。支持本地部署，完全免费，无版权限制，是技术用户和需要完全控制权的创作者的首选。",
        price: "免费（本地部署）",
        rating: 4.4,
        url: "https://stability.ai",
        featured: false,
        pros: ["完全免费开源", "可本地部署", "无版权限制", "社区插件丰富"],
        cons: ["需要一定技术门槛", "部署硬件要求高", "出图需调参"],
        bestFor: ["技术用户", "需要完全控制权", "批量生成", "研究学习"],
        alternatives: ["midjourney", "leonardo", "ideogram-v2"]
    },
    {
        id: "sora",
        name: "OpenAI Sora",
        icon: "🎬",
        tag: "AI视频",
        category: "video",
        description: "OpenAI推出的文本生成视频模型，支持最长60秒高质量视频生成，物理模拟和世界模型能力强，画面连贯性和真实感处于行业顶尖水平。仅限ChatGPT Plus/Pro用户使用。",
        price: "ChatGPT Plus $20/月含",
        rating: 4.7,
        url: "https://openai.com/sora",
        featured: true,
        pros: ["最长60秒生成", "画质业界顶尖", "世界模型能力强", "支持中文提示词"],
        cons: ["仅限Plus/Pro用户", "排队时间较长", "编辑功能较弱"],
        bestFor: ["概念视频", "创意短片", "广告创意", "视觉实验"],
        alternatives: ["runway-gen3", "pika", "kling"]
    },
    {
        id: "kling",
        name: "可灵AI (Kling)",
        icon: "🇨🇳",
        tag: "AI视频",
        category: "video",
        description: "快手推出的AI视频生成模型，支持文生视频和图生视频，对中文提示词理解优秀，免费额度 generous，是国内用户最友好的AI视频工具之一。",
        price: "免费 + ¥60/月起",
        rating: 4.5,
        url: "https://kling.ai",
        featured: true,
        pros: ["原生中文支持", "免费额度多", "国内访问快", "图生视频效果好"],
        cons: ["最长10秒限制", "画质略逊Sora", "海外知名度较低"],
        bestFor: ["中文创作者", "短视频制作", "国内用户", "图生视频"],
        alternatives: ["runway-gen3", "sora", "pika"]
    },
    {
        id: "pika",
        name: "Pika Labs",
        icon: "⚡",
        tag: "AI视频",
        category: "video",
        description: "新兴AI视频生成工具，支持文生视频、图生视频、视频局部编辑（Inpainting），操作简便，社区活跃，适合快速制作短视频素材和创意实验。",
        price: "免费 + $10/月",
        rating: 4.2,
        url: "https://pika.art",
        featured: false,
        pros: ["免费版可用", "视频编辑功能独特", "操作简单", "社区活跃"],
        cons: ["视频时长较短", "画质不如顶级工具", "生成速度中等"],
        bestFor: ["短视频素材", "视频局部编辑", "创意实验", "社交媒体内容"],
        alternatives: ["runway-gen3", "sora", "kling"]
    },
    {
        id: "sunoo",
        name: "Suno AI",
        icon: "🎵",
        tag: "AI音乐",
        category: "audio",
        description: "领先的AI音乐生成工具，支持通过文字描述生成完整歌曲（含旋律、编曲、人声），支持多种风格和语言，是制作背景音乐和创意歌曲的强大工具。",
        price: "免费 + $10/月",
        rating: 4.6,
        url: "https://suno.com",
        featured: true,
        pros: ["生成完整歌曲", "多种音乐风格", "支持中文歌词", "旋律质量高"],
        cons: ["免费版有水印", "人声偶尔不清晰", "高级编辑功能有限"],
        bestFor: ["背景音乐制作", "创意歌曲", "自媒体配乐", "音乐实验"],
        alternatives: ["udio", "elevenlabs"]
    },
    {
        id: "murf-ai",
        name: "Murf AI",
        icon: "🎙️",
        tag: "AI配音",
        category: "audio",
        description: "专业级AI语音合成和配音工具，提供120+语言和口音，支持情感调节、语速控制、停顿编辑，广泛应用于企业培训、有声书、视频配音等商业场景。",
        price: "$19/月起",
        rating: 4.3,
        url: "https://murf.ai",
        featured: false,
        pros: ["120+语言口音", "情感调节精细", "商业授权清晰", "视频时间轴同步"],
        cons: ["免费版功能有限", "价格较高", "中文情感不如英文自然"],
        bestFor: ["企业培训视频", "有声书配音", "广告配音", "多语言内容"],
        alternatives: ["elevenlabs", "azure-tts", "google-tts"]
    },
  {
        id: "notion-ai",
        name: "Notion AI",
        icon: "📝",
        tag: "效率工具",
        category: "productivity",
        description: "Notion集成的AI助手，可在笔记、文档、知识库中直接调用AI进行写作、总结、翻译和问答，无缝融入工作流，是知识管理和内容创作的得力助手。",
        price: "$10/月（加Notion订阅）",
        rating: 4.3,
        url: "https://notion.so",
        featured: false,
        pros: ["与Notion深度集成", "支持多种AI任务", "上下文理解强", "团队协作友好"],
        cons: ["需要Notion付费版", "AI功能需额外付费", "大文档处理慢"],
        bestFor: ["知识管理", "团队协作文档", "会议纪要", "内容规划"],
        alternatives: ["mem", "reflect", "logseq"]
    },
    {
        id: "canva-ai",
        name: "Canva AI (Magic Studio)",
        icon: "🎨",
        tag: "设计工具",
        category: "productivity",
        description: "Canva集成的AI设计套件（Magic Studio），包含AI图片生成、智能抠图、一键翻译、Magic Resize等功能，让非设计师也能快速制作专业级设计。",
        price: "免费 + Pro ¥59/月",
        rating: 4.5,
        url: "https://www.canva.com",
        featured: true,
        pros: ["模板库极丰富", "AI功能覆盖全面", "操作简单易上手", "支持中文"],
        cons: ["Pro版价格较高", "高级AI功能需付费", "印刷质量有限"],
        bestFor: ["社交媒体图", "演示文稿", "海报传单", "快速设计"],
        alternatives: ["adobe-firefly", "leonardo", "midjourney"]
    },
    {
        id: "semrush-ai-writing",
        name: "Semrush SEO Writing Assistant",
        icon: "📈",
        tag: "营销工具",
        category: "marketing",
        description: "Semrush推出的AI写作助手，集成SEO优化建议，帮助创作符合搜索引擎排名要求的高质量内容，实时内容评分系统帮助用户持续优化，是内容营销和SEO团队的利器。",
        price: "包含在Semrush订阅中（$139.95/月）",
        rating: 4.1,
        url: "https://semrush.com",
        featured: false,
        pros: ["深度SEO集成", "实时优化建议", "关键词研究联动", "内容评分系统"],
        cons: ["Semrush订阅价格高", "适合SEO专业人士", "学习成本较高"],
        bestFor: ["SEO内容创作", "博客优化", "竞品分析", "关键词策略"],
        alternatives: ["surfer-seo", "clearscope", "jasper"]
    },
    {
        id: "hubspot-ai",
        name: "HubSpot AI",
        icon: "🤝",
        tag: "营销工具",
        category: "marketing",
        description: "HubSpot CRM集成的AI营销助手，覆盖邮件营销、内容创作、客户分析、聊天机器人等全链路营销场景，帮助企业提升营销效率和客户转化率。",
        price: "免费版 + 付费版按需",
        rating: 4.2,
        url: "https://hubspot.com",
        featured: false,
        pros: ["与CRM深度集成", "覆盖全营销链路", "免费版功能丰富", "数据驱动决策"],
        cons: ["高级功能价格高", "学习曲线较陡", "适合有一定规模的企业"],
        bestFor: ["邮件营销", "客户管理", "内容营销", "销售自动化"],
        alternatives: ["jasper", "semrush-ai-writing", "copyai"]
    },
    {
        id: "replit-ai",
        name: "Replit AI",
        icon: "🌐",
        tag: "AI编程",
        category: "code",
        description: "在线IDE Replit集成的AI编程助手，支持自然语言描述生成完整应用，内置部署功能，是零基础用户学习编程和快速原型开发的最佳平台。",
        price: "免费 + Core $20/月",
        rating: 4.6,
        url: "https://replit.com",
        featured: true,
        pros: ["零基础可上手", "自然语言生成应用", "内置部署托管", "协作功能强大"],
        cons: ["免费版运行时间有限", "复杂项目需付费", "服务器在国外"],
        bestFor: ["快速原型", "学习编程", "全栈项目", "团队协作"],
        alternatives: ["cursor", "github-copilot", "codeium"]
    }
];

// 博客文章数据
const BLOG_POSTS = [
    {
        id: "free-ai-tools-2026",
        title: "2026年最值得使用的免费AI工具大全（实测推荐）",
        date: "2026-05-20",
        summary: "精选16款真正免费好用的AI工具，覆盖对话、绘画、编程、写作、视频、音频六大领域，零成本提升工作效率。",
        category: "资源汇总",
        tags: ["免费AI工具", "ChatGPT", "AI绘画", "AI编程"],
        image: "💎"
    },
    {
        id: "ai-video-tools-guide",
        title: "2026年AI视频生成工具完全指南：Runway、Sora、Pika谁更强？",
        date: "2026-05-20",
        summary: "全面评测Runway Gen-3、Sora、可灵AI、Pika等主流AI视频工具，从画质、价格、中文支持多维度对比。",
        category: "选购指南",
        tags: ["AI视频", "Runway", "Sora", "可灵AI"],
        image: "🎬"
    },
    {
        id: "ai-beginners-guide",
        title: "AI初学者完全入门指南：从零开始掌握AI工具",
        date: "2026-05-20",
        summary: "零基础AI入门教程，从注册到提示词技巧，手把手教你掌握ChatGPT、AI绘画等主流工具。",
        category: "入门教程",
        tags: ["AI入门", "ChatGPT教程", "新手指南"],
        image: "🚀"
    },
    {
        id: "chatgpt-vs-claude-2026",
        title: "ChatGPT vs Claude 2026：哪个AI对话助手更适合你？",
        date: "2026-05-19",
        summary: "深度对比ChatGPT和Claude在推理、写作、编程、价格等方面的表现，帮你选出最适合的AI助手。",
        category: "评测对比",
        tags: ["ChatGPT", "Claude", "AI对话"],
        image: "📊"
    },
    {
        id: "ai-image-tools-guide",
        title: "2026年最佳AI绘画工具完全指南",
        date: "2026-05-17",
        summary: "从Midjourney到Leonardo，全面评测12款AI绘画工具，涵盖画质、价格、易用性等多维度对比。",
        category: "选购指南",
        tags: ["AI绘画", "Midjourney", "Stable Diffusion"],
        image: "🎨"
    },
    {
        id: "ai-coding-tools-comparison",
        title: "AI编程工具横评：Copilot、Cursor、Codeium谁更强？",
        date: "2026-05-15",
        summary: "实测对比三款主流AI编程助手，从代码质量、IDE集成、价格等角度给出选购建议。",
        category: "工具评测",
        tags: ["AI编程", "GitHub Copilot", "Cursor"],
        image: "💻"
    },
    {
        id: "ai-tools-for-marketers",
        title: "营销人必备：10款提升ROI的AI工具",
        date: "2026-05-18",
        summary: "精选10款适合营销团队的AI工具，覆盖内容创作、SEO优化、数据分析、广告投放等核心场景。",
        category: "应用场景",
        tags: ["营销AI", "内容创作", "SEO"],
        image: "📈"
    }
];

// 分类数据
const CATEGORIES = {
    writing: { name: "AI写作", icon: "✍️", count: 1 },
    image: { name: "AI绘画", icon: "🎨", count: 5 },
    video: { name: "AI视频", icon: "🎬", count: 4 },
    code: { name: "AI编程", icon: "💻", count: 3 },
    chat: { name: "AI对话", icon: "💬", count: 5 },
    audio: { name: "AI音频", icon: "🎵", count: 3 },
    productivity: { name: "效率工具", icon: "⚡", count: 3 },
    marketing: { name: "营销工具", icon: "📈", count: 3 }
};
