// js/tools-data.js - AI工具数据库
const TOOLS_DATA = [
    {
        id: "chatgpt",
        name: "ChatGPT",
        icon: "💬",
        tag: "AI对话",
        category: "chat",
        description: "OpenAI开发的知名AI对话助手，支持文字、图片、语音多模态交互，可用于写作、编程、翻译、分析等各类任务。",
        price: "免费 + Plus $20/月",
        rating: 4.8,
        url: "https://chat.openai.com",
        featured: true,
        pros: ["强大的逻辑推理能力", "支持插件扩展", "多模态输入支持", "活跃的开发者社区"],
        cons: ["免费版有使用限制", "偶尔服务器繁忙", "数据隐私存在争议"],
        bestFor: ["内容创作", "编程辅助", "学习研究", "日常问答"],
        alternatives: ["claude", "gemini", "perplexity"]
    },
    {
        id: "claude",
        name: "Claude",
        icon: "🤖",
        tag: "AI对话",
        category: "chat",
        description: "Anthropic公司开发的AI助手，以安全性、可控性和长上下文窗口著称，擅长长文档分析和精确写作。",
        price: "免费 + Pro $20/月",
        rating: 4.7,
        url: "https://claude.ai",
        featured: true,
        pros: ["200K超长上下文", "更安全的输出", "擅长分析和写作", "引用来源可追溯"],
        cons: ["创意写作不如GPT-4", "部分地区访问受限"],
        bestFor: ["长文档分析", "学术研究", "内容审核", "代码审查"],
        alternatives: ["chatgpt", "gemini"]
    },
    {
        id: "midjourney",
        name: "Midjourney",
        icon: "🎨",
        tag: "AI绘画",
        category: "image",
        description: "知名的AI图像生成工具，以高质量、艺术感强的输出著称，广泛应用于创意设计、概念艺术和营销素材制作。",
        price: "$10/月起",
        rating: 4.6,
        url: "https://midjourney.com",
        featured: true,
        pros: ["画质业界顶尖", "艺术风格丰富", "社区活跃", "版本迭代快"],
        cons: ["需要Discord使用", "无免费试用", "付费才能商用"],
        bestFor: ["概念设计", "艺术创作", "广告素材", "游戏美术"],
        alternatives: ["dalle", "stable-diffusion", "leonardo"]
    },
    {
        id: "github-copilot",
        name: "GitHub Copilot",
        icon: "💻",
        tag: "AI编程",
        category: "code",
        description: "GitHub推出的AI编程助手，深度集成VS Code等主流 IDE，提供智能代码补全、生成和重构建议。",
        price: "$10/月（学生免费）",
        rating: 4.5,
        url: "https://github.com/features/copilot",
        featured: true,
        pros: ["IDE深度集成", "支持多种编程语言", "学生免费", "GitHub生态联动"],
        cons: ["需要订阅付费", "偶尔生成有bug的代码", "依赖网络连接"],
        bestFor: ["软件开发", "代码学习", "快速原型", "重构优化"],
        alternatives: ["cursor", "codeium", "tabnine"]
    },
    {
        id: "cursor",
        name: "Cursor",
        icon: "⚡",
        tag: "AI编程",
        category: "code",
        description: "基于VS Code的AI增强代码编辑器，集成了强大的AI对话、代码生成和智能重构功能，被誉为"最懂程序员的AI工具"。",
        price: "免费 + Pro $20/月",
        rating: 4.7,
        url: "https://cursor.sh",
        featured: true,
        pros: ["基于VS Code，易上手", "AI对话式编程", "代码库级上下文理解", "免费版够用"],
        cons: ["需要联网使用AI功能", "部分高级功能需付费"],
        bestFor: ["全栈开发", "代码重构", "学习新技术", "快速迭代"],
        alternatives: ["github-copilot", "codeium"]
    },
    {
        id: "runway-gen3",
        name: "Runway Gen-3",
        icon: "🎬",
        tag: "AI视频",
        category: "video",
        description: "Runway推出的新一代AI视频生成模型，支持文本生成视频、图片转视频、视频风格迁移等功能，画质和连贯性大幅提升。",
        price: "$35/月起",
        rating: 4.4,
        url: "https://runwayml.com",
        featured: true,
        pros: ["画质业界领先", "多种视频AI功能", "风格控制精细", "API可集成"],
        cons: ["价格较高", "生成速度中等", "免费额度有限"],
        bestFor: ["短视频创作", "广告制作", "概念视频", "视觉效果"],
        alternatives: ["pika", "gen-2", "sora"]
    },
    {
        id: "notion-ai",
        name: "Notion AI",
        icon: "📝",
        tag: "效率工具",
        category: "productivity",
        description: "Notion集成的AI助手，可在笔记、文档、知识库中直接调用AI进行写作、总结、翻译和问答，无缝融入工作流。",
        price: "$10/月（加Notion订阅）",
        rating: 4.3,
        url: "https://notion.s.com",
        featured: false,
        pros: ["与Notion深度集成", "支持多种AI任务", "上下文理解强", "团队协作友好"],
        cons: ["需要Notion付费版", "AI功能需额外付费", "大文档处理慢"],
        bestFor: ["知识管理", "团队协作文档", "会议纪要", "内容规划"],
        alternatives: ["mem", "reflect", "logseq"]
    },
    {
        id: "elevenlabs",
        name: "ElevenLabs",
        icon: "🎵",
        tag: "AI音频",
        category: "audio",
        description: "知名的AI语音合成平台，提供高度自然的多语言TTS（文本转语音）和语音克隆功能，广泛应用于有声书、视频配音和虚拟助手。",
        price: "免费 + $11/月起",
        rating: 4.5,
        url: "https://elevenlabs.io",
        featured: false,
        pros: ["语音自然度极高", "支持29+语言", "语音克隆功能强大", "API接入方便"],
        cons: ["付费版才支持商用", "克隆语音需谨慎使用", "免费版额度有限"],
        bestFor: ["视频配音", "有声书制作", "虚拟主播", "客服语音"],
        alternatives: ["azure-tts", "google-tts", "amazon-polly"]
    },
    {
        id: "jasper",
        name: "Jasper AI",
        icon: "✍️",
        tag: "AI写作",
        category: "writing",
        description: "面向企业和营销团队的AI写作工具，擅长生成广告文案、博客文章、社交媒体内容和邮件营销文案，支持Brand Voice定制。",
        price: "$49/月起",
        rating: 4.2,
        url: "https://jasper.ai",
        featured: false,
        pros: ["营销模板丰富", "支持Brand Voice", "多语言输出", "团队协作功能"],
        cons: ["价格较高", "创意写作不如GPT-4", "学习曲线存在"],
        bestFor: ["营销文案", "企业博客", "社交媒体", "邮件营销"],
        alternatives: ["copyai", "writesonic", "chatgpt"]
    },
    {
        id: "semrush-ai",
        name: "Semrush AI Writing Assistant",
        icon: "📈",
        tag: "营销工具",
        category: "marketing",
        description: "Semrush推出的AI写作助手，集成SEO优化建议，帮助创作符合搜索引擎排名要求的高质量内容，适合内容营销和SEO团队。",
        price: "包含在Semrush订阅中（$129.95/月）",
        rating: 4.1,
        url: "https://semrush.com",
        featured: false,
        pros: ["深度SEO集成", "实时优化建议", "关键词研究联动", "内容评分系统"],
        cons: ["Semrush订阅价格高", "适合SEO专业人士", "学习成本较高"],
        bestFor: ["SEO内容创作", "博客优化", "竞品分析", "关键词策略"],
        alternatives: ["surfer-seo", "clearscope", "fasewriter"]
    },
    {
        id: "leonardo",
        name: "Leonardo.Ai",
        icon: "🖼️",
        tag: "AI绘画",
        category: "image",
        description: "新兴的AI图像生成平台，提供丰富的模型选择、精细的编辑工具和友好的免费额度，适合个人创作者和小型团队。",
        price: "免费 + $10/月起",
        rating: 4.3,
        url: "https://leonardo.ai",
        featured: false,
        pros: ["免费额度 generous", "模型选择丰富", "编辑工具强大", "社区画廊可参考"],
        cons: ["画质略逊于Midjourney", "界面相对复杂", "高级功能需付费"],
        bestFor: ["概念设计", "游戏美术", "社交媒体配图", "个人创作"],
        alternatives: ["midjourney", "stable-diffusion", "dalle"]
    },
    {
        id: "perplexity",
        name: "Perplexity AI",
        icon: "🔍",
        tag: "AI搜索",
        category: "chat",
        description: "AI驱动的搜索引擎，结合大模型对话能力和实时网络搜索，提供带引用的准确答案，是传统搜索引擎的AI升级版。",
        price: "免费 + Pro $20/月",
        rating: 4.4,
        url: "https://perplexity.ai",
        featured: false,
        pros: ["答案带引用来源", "实时网络信息", "界面简洁易用", "支持追问式搜索"],
        cons: ["深度研究能力有限", "部分高级功能需付费", "中文内容覆盖较少"],
        bestFor: ["快速调研", "事实核查", "学习新领域", "替代搜索引擎"],
        alternatives: ["chatgpt", "gemini", "you-com"]
    }
];

// 博客文章数据
const BLOG_POSTS = [
    {
        id: "chatgpt-vs-claude-2026",
        title: "ChatGPT vs Claude 2026：哪个AI对话助手更适合你？",
        date: "2026-05-19",
        summary: "深度对比ChatGPT和Claude在推理、写作、编程、价格等方面的表现，帮你选出最适合的AI助手。",
        category: "评测对比",
        tags: ["ChatGPT", "Claude", "AI对话"],
        image: "📊"
    },
    {
        id: "ai-image-tools-guide",
        title: "2026年最佳AI绘画工具完全指南",
        date: "2026-05-17",
        summary: "从Midjourney到Leonardo，全面评测12款AI绘画工具，涵盖画质、价格、易用性等多维度对比。",
        category: "选购指南",
        tags: ["AI绘画", "Midjourney", "Stable Diffusion"],
        image: "🎨"
    },
    {
        id: "ai-coding-tools-comparison",
        title: "AI编程工具横评：Copilot、Cursor、Codeium谁更强？",
        date: "2026-05-15",
        summary: "实测对比三款主流AI编程助手，从代码质量、IDE集成、价格等角度给出选购建议。",
        category: "工具评测",
        tags: ["AI编程", "GitHub Copilot", "Cursor"],
        image: "💻"
    },
    {
        id: "ai-tools-for-marketers",
        title: "营销人必备：10款提升ROI的AI工具",
        date: "2026-05-18",
        summary: "精选10款适合营销团队的AI工具，覆盖内容创作、SEO优化、数据分析、广告投放等核心场景。",
        category: "应用场景",
        tags: ["营销AI", "内容创作", "SEO"],
        image: "📈"
    }
];

// 分类数据
const CATEGORIES = {
    writing: { name: "AI写作", icon: "✍️", count: 45 },
    image: { name: "AI绘画", icon: "🎨", count: 38 },
    video: { name: "AI视频", icon: "🎬", count: 22 },
    code: { name: "AI编程", icon: "💻", count: 35 },
    chat: { name: "AI对话", icon: "💬", count: 28 },
    audio: { name: "AI音频", icon: "🎵", count: 18 },
    productivity: { name: "效率工具", icon: "⚡", count: 52 },
    marketing: { name: "营销工具", icon: "📈", count: 30 }
};
